# Generated by Django 5.0.2 on 2024-03-26 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='count_views',
            field=models.IntegerField(default=0, verbose_name='Просмотры'),
        ),
    ]
